name: Java 19 Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: gradle

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

#  test:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 23
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '19'
#          cache: gradle
#
#      - name: Run tests
#        run: ./gradlew test

#  package:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 23
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '23'
#          cache: gradle
#
#      - name: Jar with Gradle
#        run: ./gradlew jar

  docker:
     runs-on: ubuntu-latest
#     needs: test
     steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Set up JDK 19
         uses: actions/setup-java@v3
         with:
           distribution: 'temurin'
           java-version: '19'
           cache: gradle

       - name: Grant execute permission
         run: chmod +x ./gradlew

       - name: Package with Gradle
         run: ./gradlew bootJar

       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Build and push Docker image
         uses: docker/build-push-action@v4
         with:
           context: .
           file: Dockerfile
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/spring-rag:latest